### PR TITLE
First card (Quote)

### PR DESCRIPTION
**Pull request by lucidstack**
Hello there! 👋🏻 

This is a first try at a card, possibly the simplest one. Let's discuss this one out, and we can hopefully come up with a better way of structuring this and future cards! 🙇🏼

### CODE REVIEW

**Comment by spencerldixon** [comment]
Oh man that's beautiful, we should probably add something in the readme about the convention to follow when creating a card. We should also decide how much HTML should be rendered, is the content enough or will it need to render the actual card space too? I guess all cards should be responsive too

**Comment by spencerldixon** [comment]
Perhaps it should return something like this http://materializecss.com/cards.html and then let phoenix handle the larger layout of multiple cards and the sizes of each

**Comment by lucidstack** [comment]
Ah, didn't realise materializecss had an entire card section. 

I'm not sure about the responsiveness inside a card. Perhaps responsiveness should be down to the phoenix layout: 6/1, 3/2, 2/3, 1/6 layouts based on screen size, easily done with flexbox. 

Overall I think that every card should need just that:

* module with card name (`quote.ex`)
* module with API stuff to get the card data (`client.ex`)
* test client to mock calls to the APIs (`test_client.ex`)
* HTML EEx template (`template.ex`)

I added a bit of magic in the `Cards.Behaviour.__using__/1` macro, but hopefully that's clear enough, and it's anyway not strictly necessary.

**Comment by spencerldixon** [comment]
Soz m8, yes that's what I mean, the card will render the complete `<div class="card">` card but phoenix will be responsible for the rows and columns that wrap it. As long as the inside content of the card is responsive it shouldn't matter what size rows and columns it gets rendered to, and that can be decided by phoenix

**Comment by lucidstack** [comment]
Ah, that makes sense! 👌

**Pull request merged**
